# Generated by Django 4.1.5 on 2023-01-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1998-09-08'),
            preserve_default=False,
        ),
    ]
